### ISSUE TITLE
Deep Learning and Digital Image Processing courses at Technion

### ISSUE THREAD

**Issue by sankethvedula** [kmario23/deep-learning-drizzle#12]
We have amazing courses on Deep Learning and Digital Image Processing (focusing on the modern methods) at Technion, both given by Alex Bronstein.

**Deep learning**
YouTube playlist: https://www.youtube.com/watch?v=IclXQNHkYgI&list=PLM0a6Z788YAZuqg2Ip-_dPLzEd33lZvP2
Course website: https://vistalab-technion.github.io/cs236605/lectures/

**Digital Image Processing**
YouTube playlist: https://www.youtube.com/watch?v=d0Z4zRhK_Uo&list=PLM0a6Z788YAZOxUyWda9y3N_i2upIj1Ep
Course website: https://vistalab-technion.github.io/cs236860/lectures/

**Comment by kmario23** [comment]
@sankethvedula Thank you very much! I have added both of these courses :)
