### ISSUE TITLE
Deep unsupervised learning (Berkeley) and ML for CV (Heidelberg)

### ISSUE THREAD

**Issue by Mufabo** [kmario23/deep-learning-drizzle#16]
Hi,

there is a recently started course from UC Berkeley on Deep Unsupervised learning:
https://sites.google.com/view/berkeley-cs294-158-sp19/home

First lecture recording on youtube:
https://www.youtube.com/watch?v=zNmvH6OXDpk&feature=youtu.be

Machine Learning for Computer Vision by Fred Hamprecht of Uni Heidelberg
https://www.youtube.com/playlist?list=PLuRaSnb3n4kSQFyt8VBldsQ9pO9Xtu8rY

**Comment by kmario23** [comment]
Thanks! Added both of these courses :)
