### ISSUE TITLE
Adding a few more courses.

### ISSUE THREAD

**Issue by Shashi456** [kmario23/deep-learning-drizzle#19]
Stanford NLP 2019 edition.
https://www.youtube.com/playlist?list=PLoROMvodv4rOhcuXMZkNm7j3fVwBBY42z&fbclid=IwAR2f5afK7gZkP98Zlw06P7lN1OkqwV4FC7Xu0g38Y4oetiiThZJf8j8k348

Summer School
http://videolectures.net/DLRLsummerschool2018_toronto/
http://videolectures.net/deeplearning2017_montreal/

Finally, i think you could start adding links of conference videos, like workshops or invited talks.
For example, https://nips.cc/Conferences/2018/Videos OR https://videoken.com/embed

Amazing job on the work done so far.

Finally @kmario23 NYU has a new course on Responsible Data Science. Although there are no lectures available. The material itself is a huge resource for Ethical DL. since there are no other courses i implore you to do so xD. the link is https://dataresponsibly.github.io/courses/spring19/

**Comment by kmario23** [comment]
Hi @Shashi456 , thank you! I have updated these courses. Regarding your last point: this repo is mainly about video-based courses/schools. I intend to keep it that way for now :) Please add an issue if you find more courses (with video lectures).
