### ISSUE TITLE
Not an issue(Adding a course)

### ISSUE THREAD

**Issue by imr555** [kmario23/deep-learning-drizzle#20]
First of I want to start by saying this is an amazing compilation.I recently came across this course by Joseph Redmon(Famous For Darknet framework and his amusing resume),

Playlist
`https://www.youtube.com/watch?v=8jXIAWg_yHU&list=PLjMXczUzEYcHvw5YYSU92WrY8IwhTuq7p`

CoursePage
`https://pjreddie.com/courses/computer-vision/`

It seemed to cover some awesome  aspects of computer vision. Thought it might be cool to add to this compilation.

**Comment by kmario23** [comment]
thanks @imr555, done!
