### ISSUE TITLE
adding more courses and a suggestions

### ISSUE THREAD

**Issue by efirvida** [kmario23/deep-learning-drizzle#28]
Hello, first of all, I want to thank for all the info linked on this thread.
 I found this guy on youtube who has a lot of playlist and courses about the machine and deep learning.

and other things too, but not related.

1. https://www.youtube.com/watch?v=OGxgnH8y2NM&list=PLQVvvaa0QuDfKTOs3Keq_kaG2P55YRn5v
2. https://www.youtube.com/watch?v=wQ8BIBpya2k&list=PLQVvvaa0QuDfhTox0AjmQ6tvTgMBZBEXN
3. https://www.youtube.com/watch?v=FLZvOKSCkxY&list=PLQVvvaa0QuDf2JswnfiGkliBInZnIC4HL
4. https://www.youtube.com/watch?v=URTZ2jKCgBc&list=PLQVvvaa0QuDd0flgGphKCej-9jp-QdzZ3
5. https://www.youtube.com/watch?v=v_L9jR8P-54&list=PLQVvvaa0QuDe6ZBtkCNWNUbdaBo2vA4RO
6. https://www.youtube.com/watch?v=yMk_XtIEzH8&list=PLQVvvaa0QuDezJFIOU5wDdfy4e9vdnx-7
7. https://www.youtube.com/watch?v=v3LJ6VvpfgI&list=PLQVvvaa0QuDcT3tPehHdisGMc8TInNqdq
8. https://www.youtube.com/watch?v=v_L9jR8P-54&list=PLQVvvaa0QuDe6ZBtkCNWNUbdaBo2vA4RO

Also, I want to suggest that you can put a brief introduction of what is and the purpose of each method to guide the people to go directly to what they want even if we don´t know what of these methods can be used to solve a specific problem.

Best

**Comment by kmario23** [comment]
Hi @efirvida,
  Thanks, but unfortunately these videos don't provide enough mathematical contents.The primary goal of this repo is to organize only lectures which offer some mathematical insights.
