### ISSUE TITLE
ML course - Probabilistic Graphical Models

### ISSUE THREAD

**Issue by DWhettam** [kmario23/deep-learning-drizzle#3]
I'd include [Daphne Koller's course on Probabilistic Graphical Models](https://www.coursera.org/learn/probabilistic-graphical-models). There currently isn't anything from a probabilistic perspective in the ML section, so definitely worth including.

**Comment by kmario23** [comment]
@DWhettam Thank you for the suggestion! I've included a PGM section, which is indeed a foundation for Graph Neural Networks, and added a few courses. However, I couldn't find the videos of Daphne Koller's course in public domain. Please do send me if you can find it!

**Comment by DWhettam** [comment]
You can audit the course and access all of the lectures through the link I gave. You just can't do any of the assignments
