### ISSUE TITLE
Lecture Links

### ISSUE THREAD

**Issue by tathatj** [kmario23/deep-learning-drizzle#31]
1.Speech Recognition - https://www.youtube.com/channel/UCHk6uq1Cr9J3k5KNmIsYUNw/videos
2.Numerical Optimization - https://www.youtube.com/playlist?list=PL6EA0722B99332589
3.Machine Learning for Structured Data-https://www.youtube.com/playlist?list=PL4CxkUJbvNVihRKP4bXufvRLIWzeS-ieP
4.Machine Intelligence-https://www.youtube.com/playlist?list=PL4upCU5bnihwCX93Gv6AQnKmVMwx4AZoT
5.Advanced Machine Learning-https://www.cs.cornell.edu/courses/cs6780/2019sp/

**Comment by kmario23** [comment]
@tathatj  Vielen Dank! :)

**Comment by tathatj** [comment]
> 
> 
> @tathatj Vielen Dank! :)

Some more new links:
1)CS 152: Neural Networks/Deep Learning—Fall, 2019
https://www.youtube.com/playlist?list=PLgEuVSRbAI9UIQSHGy4l01laA_12YOqEj
2)Deep Learning ETH Zurich fall 2019
https://video.ethz.ch/lectures/d-infk/2019/autumn/263-3210-00L.html
http://www.da.inf.ethz.ch/teaching/2019/DeepLearning/

**Comment by kmario23** [comment]
@tathatj thank ya! added these, and more :)
