### ISSUE TITLE
PGM New CMU Course

### ISSUE THREAD

**Issue by BirkhoffG** [kmario23/deep-learning-drizzle#32]
CMU has uploaded a new PGM course in 2019 by Eric Xing. Highly recommended! link: https://sailinglab.github.io/pgm-spring-2019/

**Comment by kmario23** [comment]
@BirkhoffG Indeed, a re-offering after 15 years! Thank you very much, added :)

**Comment by tathatj** [comment]
Add the youtube link
https://www.youtube.com/playlist?list=PLoZgVqqHOumTY2CAQHL45tQp6kmDnDcqn
