### ISSUE TITLE
Add link to Blog

### ISSUE THREAD

**Issue by rajtilak82** [kmario23/deep-learning-drizzle#35]
Add the following link for the Tableau Dashboard:

[https://www.hashtagtechgeek.com/2019/10/250-machine-learning-deep-learning-videos-courseware.html](https://www.hashtagtechgeek.com/2019/10/250-machine-learning-deep-learning-videos-courseware.html)

**Comment by kmario23** [comment]
@rajtilak82 thanks a lot! Added it in `Around the Web` section :)

**Comment by rajtilak82** [comment]
Thank you very much!

**Comment by kmario23** [comment]
@rajtilak82 I've noticed that some of the links in Tableau Dashboard are stale; Please feel free to update it with the new `readme.md`, if it's not too much work :)

**Comment by rajtilak82** [comment]
Will do, thank for the update.

Regards,
Raj
Rajtilak Bhattacharjee

*"At the touch of love, everyone becomes a poet." - Plato*
#TechGeek <https://www.hashtagtechgeek.com>
