### ISSUE TITLE
Consider adding CS285: Deep Reinforcement Learning, UC Berkeley | Fall 2019

### ISSUE THREAD

**Issue by georgezoto** [kmario23/deep-learning-drizzle#42]
CS285: Deep Reinforcement Learning, UC Berkeley | Fall 2019
Lecture Series, YouTube: https://www.youtube.com/playlist?list=PLkFD6_40KJIwhWJpGazJ9VSj9CFMkb79A

**Comment by kmario23** [comment]
@georgezoto Thanks a bunch, added!
