### ISSUE TITLE
New lectures

### ISSUE THREAD

**Issue by tathatj** [kmario23/deep-learning-drizzle#43]
1. Deep Learning for Computer Vision (Fall 2019)
https://web.eecs.umich.edu/~justincj/teaching/eecs498/
http://leccap.engin.umich.edu/leccap/site/jhygcph151x25gjj1f0

2. Designing, Visualizing and Understanding Deep Neural Networks (Spring 2020)
https://bcourses.berkeley.edu/courses/1487769/pages/cs-l-w-182-slash-282a-designing-visualizing-and-understanding-deep-neural-networks-spring-2020
https://www.youtube.com/playlist?list=PLkFD6_40KJIwaO6Eca8kzsEFBob0nFvwm

3. DEEP LEARNING (DS-GA 1008 · SPRING 2020)
https://atcold.github.io/pytorch-Deep-Learning/
https://www.youtube.com/playlist?list=PLLHTzKZzVU9eaEyErdV26ikyolxOsz6mq

4. CS165: Foundations of Machine Learning and Statistical Inference
http://tensorlab.cms.caltech.edu/users/anima/cms165-2020.html
https://www.youtube.com/user/msagopa/videos

**Comment by mo-zahran** [comment]
5. CS 330: Deep Multi-Task and Meta-Learning
     https://cs330.stanford.edu/
     https://www.youtube.com/playlist?list=PLoROMvodv4rMC6zfYmnD7UG3LVvwaITY5

**Comment by mo-zahran** [comment]
6. CS294-158-SP20 Deep Unsupervised Learning Spring 2020
    https://sites.google.com/view/berkeley-cs294-158-sp20/home
    https://www.youtube.com/playlist?list=PLwRJQ4m4UJjPiJP3691u-qWwPGVKzSlNP

**Comment by mo-zahran** [comment]
7. CS 188 | Introduction to Artificial Intelligence
https://inst.eecs.berkeley.edu/~cs188/fa18/
https://www.youtube.com/playlist?list=PL7k0r4t5c108AZRwfW-FhnkZ0sCKBChLH

**Comment by mo-zahran** [comment]
8. CS221: Artificial Intelligence: Principles and Techniques
https://stanford-cs221.github.io/autumn2019/
https://www.youtube.com/playlist?list=PLoROMvodv4rO1NB9TD4iUZ3qghGEGtqNX

9. CPSC 322: Introduction to Artificial Intelligence (UBC)
https://www.youtube.com/playlist?list=PLDPnGbm0sUmpzvcGvktbz446SLdFbfZVU

**Comment by mo-zahran** [comment]
10. Machine Learning 10-601, Spring 2015 Carnegie Mellon University
http://www.cs.cmu.edu/~ninamf/courses/601sp15/lectures.shtml

11. Probabilistic Graphical Models Spring 2019 Carnegie Mellon University
https://sailinglab.github.io/pgm-spring-2019/lectures/
https://www.youtube.com/playlist?list=PLoZgVqqHOumTY2CAQHL45tQp6kmDnDcqn

12. Probabilistic Graphical Models Spring 2020 Carnegie Mellon University
https://www.cs.cmu.edu/~epxing/Class/10708-20/lectures.html
https://www.youtube.com/playlist?list=PLoZgVqqHOumTqxIhcdcpOAJOOimrRCGZn

13. 11-785 Introduction to Deep Learning Spring 2020 Carnegie Mellon University
https://deeplearning.cs.cmu.edu/
https://www.youtube.com/playlist?list=PLp-0K3kfddPzCnS4CqKphh-zT3aDwybDe

14. 11-785 Introduction to Deep Learning Spring 2019 Carnegie Mellon University
https://www.cs.cmu.edu/~bhiksha/courses/deeplearning/Spring.2019/www/
https://www.youtube.com/playlist?list=PLp-0K3kfddPwz13VqV1PaMXF6V6dYdEsj

15. Convex Optimization: Fall 2018 Carnegie Mellon University
https://www.stat.cmu.edu/~ryantibs/convexopt-F18/

16. Convex Optimization: Fall 2015 Carnegie Mellon University
stat.cmu.edu/~ryantibs/convexopt-F15/

17. Convex Optimization: Spring 2015 Carnegie Mellon University
https://www.stat.cmu.edu/~ryantibs/convexopt-S15/

18. Convex Optimization: Fall 2016 Carnegie Mellon University
https://www.stat.cmu.edu/~ryantibs/convexopt-F16/

19. Statistical Machine Learning: Spring 2017
https://www.stat.cmu.edu/~ryantibs/statml/

20. 10-725 Optimization Fall 2012 Carnegie Mellon University
https://www.youtube.com/playlist?list=PL7y-1rk2cCsDOv91McLOnV4kExFfTB7dU

21. 10-606 and 10-607 Math Background for ML, Fall 2017
https://canvas.cmu.edu/courses/603/assignments/syllabus
https://www.youtube.com/playlist?list=PL7y-1rk2cCsAqRtWoZ95z-GMcecVG5mzA

22. Advanced Introduction to Machine Learning 10-715 Carnegie Mellon University
https://www.cs.cmu.edu/~bapoczos/Classes/ML10715_2015Fall/
https://www.youtube.com/playlist?list=PL4YhK0pT0ZhWBzSBkMGzpnPw6sf6Ma0IX

**Comment by mo-zahran** [comment]
23. 15-780 Graduate Artificial Intelligence | CMU
https://www.youtube.com/playlist?list=PL_Ig1a5kxu55zgIn3Tb5Pc5C62Yo2sYHf
http://www.cs.cmu.edu/~arielpro/15780s18/index.html

24. CMU 10-605 Machine Learning With Large Datasets
https://www.youtube.com/playlist?list=PLnfBqXRW5MRhPtfkadfwQ0VcuSi2IwEcW

**Comment by kmario23** [comment]
> 1. Deep Learning for Computer Vision (Fall 2019)
>    https://web.eecs.umich.edu/~justincj/teaching/eecs498/
>    http://leccap.engin.umich.edu/leccap/site/jhygcph151x25gjj1f0
> 2. Designing, Visualizing and Understanding Deep Neural Networks (Spring 2020)
>    https://bcourses.berkeley.edu/courses/1487769/pages/cs-l-w-182-slash-282a-designing-visualizing-and-understanding-deep-neural-networks-spring-2020
>    https://www.youtube.com/playlist?list=PLkFD6_40KJIwaO6Eca8kzsEFBob0nFvwm
> 3. DEEP LEARNING (DS-GA 1008 · SPRING 2020)
>    https://atcold.github.io/pytorch-Deep-Learning/
>    https://www.youtube.com/playlist?list=PLLHTzKZzVU9eaEyErdV26ikyolxOsz6mq
> 4. CS165: Foundations of Machine Learning and Statistical Inference
>    http://tensorlab.cms.caltech.edu/users/anima/cms165-2020.html
>    https://www.youtube.com/user/msagopa/videos

@tathatj thanks a bunch!! Updated all of these. I've been traveling, hence the delay.

**Comment by kmario23** [comment]
> 1. Machine Learning 10-601, Spring 2015 Carnegie Mellon University
>    http://www.cs.cmu.edu/~ninamf/courses/601sp15/lectures.shtml
> 2. Probabilistic Graphical Models Spring 2019 Carnegie Mellon University
>    https://sailinglab.github.io/pgm-spring-2019/lectures/
>    https://www.youtube.com/playlist?list=PLoZgVqqHOumTY2CAQHL45tQp6kmDnDcqn
> 3. Probabilistic Graphical Models Spring 2020 Carnegie Mellon University
>    https://www.cs.cmu.edu/~epxing/Class/10708-20/lectures.html
>    https://www.youtube.com/playlist?list=PLoZgVqqHOumTqxIhcdcpOAJOOimrRCGZn
> 4. 11-785 Introduction to Deep Learning Spring 2020 Carnegie Mellon University
>    https://deeplearning.cs.cmu.edu/
>    https://www.youtube.com/playlist?list=PLp-0K3kfddPzCnS4CqKphh-zT3aDwybDe
> 5. 11-785 Introduction to Deep Learning Spring 2019 Carnegie Mellon University
>    https://www.cs.cmu.edu/~bhiksha/courses/deeplearning/Spring.2019/www/
>    https://www.youtube.com/playlist?list=PLp-0K3kfddPwz13VqV1PaMXF6V6dYdEsj
> 6. Convex Optimization: Fall 2018 Carnegie Mellon University
>    https://www.stat.cmu.edu/~ryantibs/convexopt-F18/
> 7. Convex Optimization: Fall 2015 Carnegie Mellon University
>    stat.cmu.edu/~ryantibs/convexopt-F15/
> 8. Convex Optimization: Spring 2015 Carnegie Mellon University
>    https://www.stat.cmu.edu/~ryantibs/convexopt-S15/
> 9. Convex Optimization: Fall 2016 Carnegie Mellon University
>    https://www.stat.cmu.edu/~ryantibs/convexopt-F16/
> 10. Statistical Machine Learning: Spring 2017
>     https://www.stat.cmu.edu/~ryantibs/statml/
> 11. 10-725 Optimization Fall 2012 Carnegie Mellon University
>     https://www.youtube.com/playlist?list=PL7y-1rk2cCsDOv91McLOnV4kExFfTB7dU
> 12. 10-606 and 10-607 Math Background for ML, Fall 2017
>     https://canvas.cmu.edu/courses/603/assignments/syllabus
>     https://www.youtube.com/playlist?list=PL7y-1rk2cCsAqRtWoZ95z-GMcecVG5mzA
> 13. Advanced Introduction to Machine Learning 10-715 Carnegie Mellon University
>     https://www.cs.cmu.edu/~bapoczos/Classes/ML10715_2015Fall/
>     https://www.youtube.com/playlist?list=PL4YhK0pT0ZhWBzSBkMGzpnPw6sf6Ma0IX

Hey @mo-zahran, thanks a lot for putting effort with this!! Really appreciated :) I have added all of these except for general AI courses. Since I was unsure about the category, I've left it for now..
