### ISSUE TITLE
New Deep Unsupervised Learning  Course

### ISSUE THREAD

**Issue by tandelDipak** [kmario23/deep-learning-drizzle#44]
Deep Unsupervised Learning Course from Berkeley : [ https://sites.google.com/view/berkeley-cs294-158-sp20/home]( https://sites.google.com/view/berkeley-cs294-158-sp20/home)

You can create a new section for Unsupervised learning or add it to the deep learning section.

**Comment by kmario23** [comment]
Hey @tandelDipak ,
  It's already up on [deep-learning-drizzle.github.io](https://deep-learning-drizzle.github.io/)!
