### ISSUE TITLE
fast.ai missing

### ISSUE THREAD

**Issue by LeonardoDipilato** [kmario23/deep-learning-drizzle#5]
[fast.ai v3](https://course.fast.ai/index.html), **DL**, with part 2 coming, although part 1 covers a lot of topic;
[Introduction to Machine Learning for Coders](http://course18.fast.ai/ml.html), **ML**.

**Comment by kmario23** [comment]
@LeonardoDipilato thanks for your suggestion! Since this is a highly practical course, I will create a separate section for this and add it there.

**Comment by LeonardoDipilato** [comment]
Oh, I didn't notice you were focusing on theory. Either way, issue closed.
