### ISSUE TITLE
Advanced NLP course by UMass

### ISSUE THREAD

**Issue by ambujmittal** [kmario23/deep-learning-drizzle#50]
Course Name: CS 685: Advanced Natural Language Processing, Fall 2020.
Instructor: Mohit Iyyer, UMass.
Course WebPage: https://people.cs.umass.edu/~miyyer/cs685/index.html
Lecture Videos: https://www.youtube.com/playlist?list=PLWnsVgP6CzadmQX6qevbar3_vDBioWHJL
Year: Fall, 2020

**Comment by kmario23** [comment]
Hey @ambujmittal , I've added. Thank you!
