### ISSUE TITLE
MIT Machine Learning Courses

### ISSUE THREAD

**Issue by mzahran001** [kmario23/deep-learning-drizzle#55]
MIT 6.S897 Machine Learning for Healthcare, Spring 2019
View the complete course: https://ocw.mit.edu/6-S897S19

https://www.youtube.com/playlist?list=PLUl4u3cNGP60B0PQXVQyGNdCyCTDU1Q5j

**Comment by mzahran001** [comment]
MIT RES.EC-001 Exploring Fairness in Machine Learning, Spring 2020
https://www.youtube.com/playlist?list=PLUl4u3cNGP63IFQn8FklBOUhYVcmaxpOX

View the complete course: https://ocw.mit.edu/RES-EC-001S20

**Comment by kmario23** [comment]
@mzahran001 added, thanks a lot!
