### ISSUE TITLE
MIT Deep Learning 6.S191

### ISSUE THREAD

**Issue by yiminzme** [kmario23/deep-learning-drizzle#57]
Hi~

<html>
<body>

Introduction to Deep Learning | Alexander Amini, Harini Suresh and others, MIT | 6.S191 | YouTube-Lectures2017-version | 2017- 2019
-- | -- | -- | -- | --

</body>
</html>

The 6.S191 is recently updated (2021 version). They have new videos available.

**Comment by kmario23** [comment]
Hello @yiminzme :handshake:,
  Sorry, the year range is not accurate. But the videos list includes both the recent and older versions.
