### ISSUE TITLE
Mathematical Tools for Data Science, NYU

### ISSUE THREAD

**Issue by moaddeli** [kmario23/deep-learning-drizzle#62]
Course Name: DS-GA 1013/Math-GA 2824: Mathematical Tools for Data Science,  2021.
Instructor: Carlos Fernandez-Granda, NYU.
Course WebPage: https://cds.nyu.edu/math-tools/
Lecture Videos: https://www.youtube.com/playlist?list=PLBEf5mJtE6KtU6YlXFZD6lyYcHhW5pIlc
Year: 2021

**Comment by kmario23** [comment]
done, thanks!
