### ISSUE TITLE
STAT 37710 / CMSC 35400: Machine Learning

### ISSUE THREAD

**Issue by moaddeli** [kmario23/deep-learning-drizzle#63]
Course Name: STAT 37710 / CMSC 35400: Machine Learning, Spring 2020.
Instructor: Rebecca Willett,  Yuxin Chen, University of Chicago.
Course WebPage: https://voices.uchicago.edu/willett/teaching/stats37710-cmsc35400-s20/
Lecture Videos: https://voices.uchicago.edu/willett/teaching/stats37710-cmsc35400-s20/
Year: Spring 2020

**Comment by kmario23** [comment]
done, thanks!
