### ISSUE TITLE
Change playlist link

### ISSUE THREAD

**Issue by tathaghosh** [kmario23/deep-learning-drizzle#64]
Please change the playlist link of "Uncertainty Modelling in AI" by NUS to the official link.
Official Link: https://www.youtube.com/playlist?list=PLxg0CGqViygOb9Eyc8IXM27doxjp2SK0H

**Comment by kmario23** [comment]
thanks @tathaghosh! Done. Sorry for the tardy response :)

**Comment by donghaiyu233** [comment]
你好，我是光学工程博士招生秘书宋岸鹏，答辩PPT已收到。
