### ISSUE TITLE
 ESE 514: Graph Neural Networks, Fall 2021

### ISSUE THREAD

**Issue by moaddeli** [kmario23/deep-learning-drizzle#66]
Course Name: ESE 514: Graph Neural Networks, Fall 2021.
Instructor: Professor Alejandro Ribeiro, University of Pennsylvania.
Course WebPage: https://gnn.seas.upenn.edu/
Lecture Videos: https://www.youtube.com/channel/UC_YPrqpiEqkeGOG1TCt0giQ/playlists
Year:  Fall 2021

**Comment by kmario23** [comment]
Grazie, added! Please feel free to send suggestions.

**Comment by donghaiyu233** [comment]
你好，我是光学工程博士招生秘书宋岸鹏，答辩PPT已收到。
