### ISSUE TITLE
Deep Learning course at UofT

### ISSUE THREAD

**Issue by bsvineethiitg** [kmario23/deep-learning-drizzle#7]
I've been absolutely loving an ongoing version of Deep Learning course by Prof. Roger Grosse at Toronto. Course contents are online here: http://www.cs.toronto.edu/~rgrosse/courses/csc421_2019/ 
Would be a great addition to the list.

**Comment by kmario23** [comment]
@bsvineethiitg His lecture's are indeed nice! However, there're no video lectures, which is the main focus of this repo. Please re-open the issue if you find the videos publicly available somewhere.
