### ISSUE TITLE
Add content relevant to MLOps

### ISSUE THREAD

**Issue by rawwar** [kmario23/deep-learning-drizzle#70]
Request - To add courses relevant to MLOps

**Comment by donghaiyu233** [comment]
你好，我是光学工程博士招生秘书宋岸鹏，答辩PPT已收到。

**Comment by bupt-wyc** [comment]
你好，你是哪个学校的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kmario23/deep-learning-drizzle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月18日(星期六) 上午10:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [kmario23/deep-learning-drizzle] Add content relevant to MLOps (Issue #70)





 你好，我是光学工程博士招生秘书宋岸鹏，答辩PPT已收到。

**Comment by donghaiyu233** [comment]
你好，我是光学工程博士招生秘书宋岸鹏，答辩PPT已收到。
