### ISSUE TITLE
Need to change link of "MIT Deep Learning"

### ISSUE THREAD

**Issue by khushbushah2302** [kmario23/deep-learning-drizzle#8]
Current link of "MIT Deep Learning" is not working.
Link of that course is : https://www.youtube.com/playlist?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf

**Comment by Aviral-Sharma-10** [comment]
May I work on the issue?

**Comment by kmario23** [comment]
> Current link of "MIT Deep Learning" is not working.
> Link of that course is : https://www.youtube.com/playlist?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf

Thank you very much for pointing this out. It has been fixed now!
